### ISSUE TITLE
Server crash after CastError

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v25-bears-team-05#118]
```
/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/error/cast.js:29
    Error.captureStackTrace(this);
          ^
CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "users"
    at new CastError (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/error/cast.js:29:11)
    at ObjectId.cast (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/schema/objectid.js:242:11)
    at ObjectId.SchemaType.applySetters (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/schematype.js:864:12)
    at ObjectId.SchemaType._castForQuery (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/schematype.js:1267:15)
    at ObjectId.SchemaType.castForQuery (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/schematype.js:1257:15)
    at ObjectId.SchemaType.castForQueryWrapper (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/schematype.js:1236:15)
    at cast (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/cast.js:307:32)
    at model.Query.Query.cast (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/query.js:4433:12)
    at model.Query.Query._castConditions (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/query.js:1762:10)
    at model.Query.<anonymous> (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/query.js:2015:8)
    at model.Query._wrappedThunk [as _findOne] (/home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at /home/lily/Documents/chingu-voyages/v25/v25-bears-team-05-repo2/node_modules/kareem/index.js:369:33
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
```

**Comment by lily-law** [comment]
Will make sure id is not undefined on client before request, but might want to handle for this on the backend too

**Comment by lily-law** [comment]
Also crashes if userId doesn't exist!
`CastError: Cast to ObjectId failed for value "5fe9f05d190e992a34dd408" at path "_id" for model "users"`

**Comment by davideastmond** [comment]
Hey do you have an idea how to reproduce this?

**Comment by lily-law** [comment]
So I'm getting it if I just change the url's user id param to something that doesn't exist
