### ISSUE TITLE
Local login email .'s get removed 

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v25-bears-team-05#143]
So emails with .'s in like `me.me@one.com` seem to convert to `meme@one.com`

We should find a way to retain the . and any other valid email symbols 

This causes a backend crash when trying to login in, looks like bcyrpt got an undefined argument somewhere: 
Edit: crash is not caused by this, it seem like another issue when trying to local login with an email also used with a google auth account
```
Error: Malformed UTF-8 data
    at Object.stringify (/Documents/chingu-voyages/v25-bears-team-05-repo2/node_modules/crypto-js/core.js:513:24)
    at WordArray.init.toString (/Documents/chingu-voyages/v25-bears-team-05-repo2/node_modules/crypto-js/core.js:268:38)
    at Object.decrypt (/Documents/chingu-voyages/v25-bears-team-05-repo2/src/utils/crypto.ts:20:18)
    at /Documents/chingu-voyages/v25-bears-team-05-repo2/src/models/password-recovery/password-recovery.methods.ts:32:7
    at Array.filter (<anonymous>)
    at Function.<anonymous> (/Documents/chingu-voyages/v25-bears-team-05-repo2/src/models/password-recovery/password-recovery.methods.ts:30:40)
    at Generator.next (<anonymous>)
    at fulfilled (/Documents/chingu-voyages/v25-bears-team-05-repo2/src/models/password-recovery/password-recovery.methods.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Error: Illegal arguments: string, undefined
    at _async (/Documents/chingu-voyages/v25-bears-team-05-repo2/node_modules/bcryptjs/dist/bcrypt.js:286:46)
    at /Documents/chingu-voyages/v25-bears-team-05-repo2/node_modules/bcryptjs/dist/bcrypt.js:307:17
    at new Promise (<anonymous>)
    at Object.bcrypt.compare (/Documents/chingu-voyages/v25-bears-team-05-repo2/node_modules/bcryptjs/dist/bcrypt.js:306:20)
    at /Documents/chingu-voyages/v25-bears-team-05-repo2/src/authentication-strategies/local-passport-strategy.ts:28:13
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by davideastmond** [comment]
Hey. I am unable to reproduce this. I tried with `david.eastmond@example.com` and the above example, `me.me@one.com` and `chole.example2.ca@example.com`. I was able to log in with each account with no error. @lily-law

**Comment by lily-law** [comment]
Humm okay so this is strange. Any example emails don't seem to do it, but by personal one does, I've completely cleared the DB so think it might display the issue on your end, will DM you the email.
